const filenames = [
  "advanced_tuck_front_lever.svg",
  "chest-to-bar_pull-up.svg",
  "chin-up.svg",
  "dips_with_box.svg",
  "front_lever_drops.svg",
  "front_lever.svg",
  "hanging_knee_raises.svg",
  "human_flag.svg",
  "one_leg_front_lever_drops.svg",
  "one_leg_front_lever.svg",
  "piked_straddle_front_lever.svg",
  "pistol_squat_box.svg",
  "pistol_squat.svg",
  "planche_push-up.svg",
  "pull-up.svg",
  "push-up.svg",
  "scapular_pulls.svg",
  "shrimp_squat.svg",
  "tuck_front_lever.svg",
  "upper-stomach-to-bar_pull-up.svg",
  "upside_down_deadlift.svg",
  "assisted_shrimp_squat.svg",
  "bulgarian_split_squat.svg",
  "cossack_squat.svg",
  "deep_squat.svg",
  "dragon_squat.svg",
  "frog_front_lever.svg",
  "front_lever_raises.svg",
  "muscle-up.svg",
  "one_leg_front_lever_raises.svg",
  "squat.svg",
  "straddle_front_lever.svg",
  "straight-bar_dips.svg",
]

export const imageOptions = filenames.map((name) => ({
  name: name.replace(/[-_]/g, ' ').replace(/\.[^/.]+$/, ''), // prettify
  url: `${import.meta.env.BASE_URL}assets/move_images/${name}`,
}))